---
- name: Setup DbServer
  hosts: dbservergrp
  become: yes
  tasks:
    - name: Install Mariadb Server(Mysql Server)
      yum:
        name: mariadb-server
        state: present

    - name: Install Mysql Python
      yum:
        name: MySQL-python
        state: present

    - name: Start and Install Mariadb-server
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: Create a new database with name 'accounts'
      mysql_db:
        name: accounts
        state: present

    - name: Create database user with name 'bob'
      mysql_user:
        name: bob
        password: 12345
        priv: '*.*:ALL'
        state: present

